import { isHexString } from "ethers";
import { BaseEntity } from "./base";
import { Utils } from "../helper";

type AddressString = string;
type HexString = string;

export interface ITopic {
  // Primary
  id?: string; // id generated by node
  ref?: string; // optional custom reference

  pTH?: string; // parent handle hash
  meta?: string; // description
  sC?: number; // subscription count
  acct?: AddressString; // owner of topic
  ts?: number; // timestamp in millisec
  pub: boolean; // is public topic
  rO: boolean;
  snet: string; // subnet
  // sig?: HexString;
  // hash?: HexString;
}

export class Topic extends BaseEntity {
  public id: string = '';
  public ref: string = '';
  public meta: string = '';
  public parentTopicHash: string = '';
  public subsriberCount: number = 0;
  public account: string = '';
  public timestamp: number = 0;
  public isPublic: boolean = false;
  public readOnly: boolean = false;
  public subnet: string = "";

  /**
   * @override
   * @returns {ITopic}
   */
  public asPayload(): ITopic {
    return {
      id: this.id,
      ref: this.ref,
      meta: this.meta,
      pTH: this.parentTopicHash, // parent handle hash
      // sC: this.subsriberCount, // subscription count
      // acct: this.account, // owner of topic
      // ts: this.timestamp, // timestamp in millisec
      pub: this.isPublic, // is public topic
      rO: this.readOnly,
      snet: this.subnet,
    };
  }

  /**
   * @override
   * @returns {Buffer}
   */
  public encodeBytes(): Buffer {
    console.log('TOPICDATA', this);
    return Utils.encodeBytes(
      { type: 'string', value: this.id },
      { type: 'string', value: this.ref },
      { type: 'string', value: this.meta },
      { type: 'hex', value: this.parentTopicHash },
      // { type: 'int', value: this.subsriberCount },
      { type: "boolean", value: this.isPublic },
      { type: "boolean", value: this.readOnly },
      { type: "string", value: this.subnet }

    );
  }
}
// ebe426ef8e11fa41d4a8e204ca49562acdef673ec0d9fafba1e86676fe06cae400000000000003e9 33363064623532362d393539322d623738632d316335632d663537613932343130383537 6469643a636f736d6f73317a3770757836706574663666766e67646b6170306370796e657a746a3577776d6c76377a39662c2387845a0e17281653050892d3095e7fc99ad32d79b7fbdf11c9a87671daca00000000000000000000018f6c288f98
// ebe426ef8e11fa41d4a8e204ca49562acdef673ec0d9fafba1e86676fe06cae400000000000003e9                                                                          6469643a636f736d6f73317a3770757836706574663666766e67646b6170306370796e657a746a3577776d6c76377a39662c2387845a0e17281653050892d3095e7fc99ad32d79b7fbdf11c9a87671daca00000000000000000000018f6c288f98
// 53325434c4de46cb58434d1325251eed7b38f64fe9d69795931aa4bae2bd5e5900000000000003e9                                                                          6469643a636f736d6f73317a3770757836706574663666766e67646b6170306370796e657a746a3577776d6c76377a39662c2387845a0e17281653050892d3095e7fc99ad32d79b7fbdf11c9a87671daca00000000000000000000018f6c319a8d
// 5c1584b323832df978796a4a1c6669b68be3414b4f1e7ace570643e1c50e828700000000000003e9                                                                          6469643a636f736d6f73317a3770757836706574663666766e67646b6170306370796e657a746a3577776d6c76377a39662c2387845a0e17281653050892d3095e7fc99ad32d79b7fbdf11c9a87671daca00000000000000000000018f6c3345c6
// 5c1584b323832df978796a4a1c6669b68be3414b4f1e7ace570643e1c50e828700000000000003e9 33363064623532362d393539322d623738632d316335632d663537613932343130383537 6469643a636f736d6f73317a3770757836706574663666766e67646b6170306370796e657a746a3577776d6c76377a39662c2387845a0e17281653050892d3095e7fc99ad32d79b7fbdf11c9a87671daca00000000000000000000018f6c3345c6