# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to dev api

on:
  push:
    branches: [publish]

  # pull_request:
  #   types: [opened, synchronize, reopened, closed]
  #   branches:
  #     - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup - Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile
      # - name: Test
      #   run: |
      #     mkdir _env
      #     cp ./ENV_TEST ./_env/.env
      #     yarn test:e2e
      - name: Deploy
        run: |
          yarn run build2
          cp package.json dist
          cd dist/ 
          yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  

